apiVersion: v1
kind: Service
metadata:
  name: application-service
  labels:
    app: webapp
spec:
  selector:
    app: webapp
  type: NodePort
  ports:
    - port: 81
      targetPort: 81
      nodePort: 30000